import turtle as tl
def f(scale):
    if scale >= 25:
         f(scale/4)
         tl.forward(scale/2)
         f(scale/4)
         tl.right(90)
         f(scale/4)
         tl.forward(scale/2)
         f(scale/4)
         tl.right(90)
         f(scale/4)
         tl.forward(scale/2)
         f(scale/4)
         tl.right(90)
         f(scale/4)
         tl.forward(scale/2)
         f(scale/4)
         tl.right(90)
    else:
        tl.forward(scale)
        tl.right(90)
        tl.forward(scale)
        tl.right(90)
        tl.forward(scale)
        tl.right(90)
        tl.forward(scale)
        tl.right(90)
        tl.forward(scale)
scale = 100
tl.pensize(2)
tl.penup()
tl.forward(-200)
tl.left(90)
tl.forward(110)
tl.right(90)
tl.pendown()
f(scale)

